/* Formatted on 9/25/2025 3:13:58 PM (QP5 v5.362) */
CREATE OR REPLACE VIEW XXSKL_AP_PAYMENT_REQUEST_FIND_DTL_V
AS
      SELECT XAP.PAPER_DOCUMENT_NUMBER,
             XAP.PAYMENT_DATE,
--             XAP.INVOICE_NUM,
             XAP.PAYEE_NAME,
             XAP.PAYMENT_AMOUNT,
--             XAP.INVOICE_AMOUNT,
             XAP.EXTERNAL_BANK_NAME,
             XAP.EXTERNAL_BANK_ACCOUNT_NUM,
             XAP.EXTERNAL_BANK_ACCOUNT_NAME,
             XAP.EXTERNAL_BANK_NUMBER,
             XAP.EXTERNAL_EFT_SWIFT_CODE,
             XAP.INQUIRY_BENEFICIARY_NAME,
             XAP.CHECK_ID,
             COUNT (XAP.INVOICE_ID)     MANY_INVOICES,
             XAP.PAYMENT_SERVICE_REQUEST_ID,
             XAP.IFACE_STATUS,
             XAP.IFACE_MESSAGE
        FROM XXSKL_AP_PAYMENT_INSTRUCTIONS XAP
       WHERE 1 = 1
    GROUP BY XAP.PAYMENT_SERVICE_REQUEST_ID,
             XAP.IFACE_STATUS,
             XAP.IFACE_MESSAGE,
             XAP.PAPER_DOCUMENT_NUMBER,
             XAP.PAYMENT_DATE,
--             XAP.INVOICE_NUM,
             XAP.PAYEE_NAME,
             XAP.PAYMENT_AMOUNT,
--             XAP.INVOICE_AMOUNT,
             XAP.EXTERNAL_BANK_NAME,
             XAP.EXTERNAL_BANK_ACCOUNT_NUM,
             XAP.EXTERNAL_BANK_ACCOUNT_NAME,
             XAP.EXTERNAL_BANK_NUMBER,
             XAP.EXTERNAL_EFT_SWIFT_CODE,
             XAP.INQUIRY_BENEFICIARY_NAME,
             XAP.CHECK_ID