/* Formatted on 9/30/2025 12:15:08 PM (QP5 v5.362) */
CREATE OR REPLACE VIEW XXSKL_AP_PAYMENT_INSTRUCTION_STATUSES_V
AS
    SELECT HEADER_ID
               HEADER_ID,
           XXSKL_AP_PAYMENT_INSTRUCTIONS_PKG.GET_STATUS_PAID (HEADER_ID)
               STATUS_PAID,
           XXSKL_AP_PAYMENT_INSTRUCTIONS_PKG.GET_BANK_BALANCE (HEADER_ID)
               BANK_BALANCE,
           XXSKL_AP_PAYMENT_INSTRUCTIONS_PKG.GET_TOTAL_AMOUNT (HEADER_ID)
               TOTAL_AMOUNT,
           XXSKL_AP_PAYMENT_INSTRUCTIONS_PKG.GET_TOTAL_PAID_AMOUNT (
               HEADER_ID)
               TOTAL_PAID_AMOUNT
      FROM XXSKL_AP_PAYMENT_HEADER_INSTRUCTIONS
     WHERE 1 = 1