/* Formatted on 9/25/2025 3:22:19 PM (QP5 v5.362) */
CREATE OR REPLACE VIEW XXSKL_AP_PAYMENT_REQUEST_FIND_INVOICES_V
AS
    SELECT XAP.CHECK_ID,
           XAP.INVOICE_NUM,
           XAP.INVOICE_AMOUNT,
           XAP.INVOICE_DATE,
           XAP.INVOICE_ID,
           XAP.IFACE_STATUS,
           XAP.IFACE_MESSAGE
      FROM XXSKL_AP_PAYMENT_INSTRUCTIONS XAP
     WHERE 1 = 1