/* Formatted on 10/10/2025 3:07:13 PM (QP5 v5.362) */
CREATE OR REPLACE VIEW XXSKL_AP_PAYMENT_INSTRUCTION_MANUAL_V
AS
      SELECT PAYMENT_PROCESS_REQUEST_NAME,
             PAYMENT_DATE,
             PAPER_DOCUMENT_NUMBER         PAYMENT_NUMBER,
             PAYMENT_PROFILE_ACCT_NAME     PAYMENT_METHOD,
             PAYMENT_AMOUNT,
             INTERNAL_BANK_ACCOUNT_NUM,
             INTERNAL_BANK_NAME,
             EXTERNAL_BANK_ACCOUNT_NUM,
             EXTERNAL_BANK_NAME,
             EXTERNAL_BANK_ACCOUNT_NAME,
             INQUIRY_BENEFICIARY_NAME,
             CHECK_ID,
             PAYMENT_INSTRUCTION_ID,
             RELEASED_DATE,
             MANUAL_DOC_TRANSFER,
             MANUAL_DOC_DESC,
             IFACE_STATUS,
             IFACE_MESSAGE
        FROM XXSKL_AP_PAYMENT_INSTRUCTIONS
       WHERE 1 = 1 AND IFACE_STATUS IN ('ERROR', 'MANUAL PAID', 'PROCESS', 'PENDING')
    GROUP BY PAYMENT_PROCESS_REQUEST_NAME,
             PAYMENT_DATE,
             PAPER_DOCUMENT_NUMBER,
             PAYMENT_PROFILE_ACCT_NAME,
             PAYMENT_AMOUNT,
             INTERNAL_BANK_ACCOUNT_NUM,
             INTERNAL_BANK_NAME,
             EXTERNAL_BANK_ACCOUNT_NUM,
             EXTERNAL_BANK_NAME,
             EXTERNAL_BANK_ACCOUNT_NAME,
             INQUIRY_BENEFICIARY_NAME,
             CHECK_ID,
             PAYMENT_INSTRUCTION_ID,
             IFACE_STATUS,
             IFACE_MESSAGE,
             RELEASED_DATE,
             MANUAL_DOC_TRANSFER,
             MANUAL_DOC_DESC
    ORDER BY PAYMENT_DATE DESC;