/* Formatted on 9/5/2025 1:28:14 PM (QP5 v5.362) */
CREATE TABLE XXSKL_AP_PAYMENT_HEADER_INSTRUCTIONS
(
    HEADER_ID                     NUMBER,
    PAYMENT_INSTRUCTION_NUMBER    VARCHAR2 (200),
    INTERNAL_BANK_ACCOUNT_ID      NUMBER,
    BANK_BALANCE                  NUMBER,
    ATTRIBUTE_CATEGORY            VARCHAR2 (300),
    ATTRIBUTE1                    VARCHAR2 (300),
    ATTRIBUTE2                    VARCHAR2 (300),
    ATTRIBUTE3                    VARCHAR2 (300),
    ATTRIBUTE4                    VARCHAR2 (300),
    ATTRIBUTE5                    VARCHAR2 (300),
    ATTRIBUTE6                    VARCHAR2 (300),
    ATTRIBUTE7                    VARCHAR2 (300),
    ATTRIBUTE8                    VARCHAR2 (300),
    ATTRIBUTE9                    VARCHAR2 (300),
    ATTRIBUTE10                   VARCHAR2 (300),
    ATTRIBUTE11                   VARCHAR2 (300),
    ATTRIBUTE12                   VARCHAR2 (300),
    ATTRIBUTE13                   VARCHAR2 (300),
    ATTRIBUTE14                   VARCHAR2 (300),
    ATTRIBUTE15                   VARCHAR2 (300),
    IFACE_MODE                    VARCHAR2 (30),
    IFACE_STATUS                  VARCHAR2 (100),
    IFACE_MESSAGE                 VARCHAR2 (4000),
    IFACE_ID                      VARCHAR2 (100),
    GROUP_ID                      VARCHAR2 (80),
    REQUEST_ID                    NUMBER,
    LOG_ID                        VARCHAR2 (100),
    CREATED_BY                    VARCHAR2 (300),
    CREATION_DATE                 DATE,
    LAST_UPDATE_LOGIN             VARCHAR2 (300),
    LAST_UPDATED_BY               VARCHAR2 (300),
    LAST_UPDATE_DATE              DATE,
    LAST_SYNC_DATE                DATE
);

CREATE UNIQUE INDEX XXSKL_AP_PAYMENT_HEADER_INSTRUCTIONS_U1
    ON XXSKL_AP_PAYMENT_HEADER_INSTRUCTIONS (HEADER_ID);
/

CREATE OR REPLACE EDITIONABLE TRIGGER XXSKL_AP_PAYMENT_HEADER_INSTRUCTIONS_TRG
    BEFORE INSERT OR UPDATE
    ON XXSKL_AP_PAYMENT_HEADER_INSTRUCTIONS
    REFERENCING NEW AS NEW OLD AS OLD
    FOR EACH ROW
BEGIN
    IF INSERTING
    THEN
        :NEW.HEADER_ID :=
            NVL (:NEW.HEADER_ID,
                 XXSKL_AP_PAYMENT_HEADER_INSTRUCTIONS_S.NEXTVAL);
        :NEW.CREATED_BY := NVL (V ('APP_USER'), USER);
        :NEW.CREATION_DATE := NVL (:NEW.CREATION_DATE, SYSDATE);
    ELSIF UPDATING
    THEN
        :NEW.LAST_UPDATED_BY := NVL (V ('APP_USER'), USER);
        :NEW.LAST_UPDATE_DATE := SYSDATE;
    END IF;
EXCEPTION
    WHEN OTHERS
    THEN
        NULL;
END XXSKL_AP_PAYMENT_HEADER_INSTRUCTIONS_TRG;
/

ALTER TRIGGER XXSKL_AP_PAYMENT_HEADER_INSTRUCTIONS_TRG
    ENABLE;
/