/* Formatted on 9/30/2025 11:02:49 PM (QP5 v5.362) */
CREATE OR REPLACE VIEW XXSKL_AP_PAYMENT_REQUEST_FIND_HDR_V
AS
      SELECT XAP.PAYMENT_PROCESS_REQUEST_NAME      PAYMENT_PROCESS_REQUEST,
             --XAP.PAYMENT_DATE,
             --             XAP.PAYMENT_DUE_DATE,
             TRUNC (XAP.CREATION_DATE)             PAYMENT_REQUEST_DATE,
             XAP.PAYMENT_CURRENCY_CODE,
             XAP.INTERNAL_BANK_ACCOUNT_NUM,
             XAP.INTERNAL_BANK_NAME,
             XAP.PAYMENT_PROFILE_ACCT_NAME,
             COUNT (DISTINCT XAP.CHECK_ID)         MANY_PAYMENTS,
             --             COUNT (XINV.COUNT_INVOICE)           MANY_INVOICES,
             SUM (DISTINCT XAP.PAYMENT_AMOUNT)     PAYMENT_AMOUNT,
             XAP.HEADER_ID,
             XAP.INTERNAL_BANK_ACCOUNT_ID,
             XAP.PAYMENT_SERVICE_REQUEST_ID
        FROM XXSKL_AP_PAYMENT_INSTRUCTIONS XAP
       --             (  SELECT COUNT (INVOICE_ID)     COUNT_INVOICE,
       --                       PAYMENT_SERVICE_REQUEST_ID
       --                  FROM XXSKL_AP_PAYMENT_INSTRUCTIONS
       --                 WHERE 1 = 1
       --              GROUP BY PAYMENT_SERVICE_REQUEST_ID) XINV
       WHERE 1 = 1
    --             AND XAP.PAYMENT_SERVICE_REQUEST_ID =
    --                 XINV.PAYMENT_SERVICE_REQUEST_ID
    --             AND XAP.IFACE_MODE IS NULL
    GROUP BY XAP.PAYMENT_PROCESS_REQUEST_NAME,
             --XAP.PAYMENT_DATE,
             --             XAP.PAYMENT_DUE_DATE,
             --             XAP.PAYMENT_AMOUNT,
             TRUNC (XAP.CREATION_DATE),
             XAP.PAYMENT_CURRENCY_CODE,
             XAP.INTERNAL_BANK_ACCOUNT_NUM,
             XAP.INTERNAL_BANK_NAME,
             XAP.PAYMENT_PROFILE_ACCT_NAME,
             XAP.HEADER_ID,
             XAP.INTERNAL_BANK_ACCOUNT_ID,
             XAP.PAYMENT_SERVICE_REQUEST_ID;