CREATE USER dev IDENTIFIED BY "KatasandiKuat123!";
GRANT CONNECT, RESOURCE, AQ_ADMINISTRATOR_ROLE TO dev;
GRANT EXECUTE ON DBMS_AQ TO dev;
GRANT EXECUTE ON DBMS_AQADM TO dev;
ALTER USER dev QUOTA UNLIMITED ON USERS;
/

BEGIN
    -- 1. Antrean Utama Keluar Aplikasi (Tipe JSON)
    DBMS_AQADM.CREATE_TRANSACTIONAL_EVENT_QUEUE(
        queue_name         => 'dev.out_q', 
        multiple_consumers => TRUE, 
        queue_payload_type => 'JSON'
    );
    DBMS_AQADM.START_QUEUE(queue_name => 'dev.out_q');
    
    -- 2. Antrean Jembatan keluar Kafka (Tipe JMS)
    DBMS_AQADM.CREATE_TRANSACTIONAL_EVENT_QUEUE(
        queue_name         => 'dev.kafka_out_q', 
        multiple_consumers => FALSE, 
        queue_payload_type => DBMS_AQADM.JMS_TYPE
    );
    DBMS_AQADM.START_QUEUE(queue_name => 'dev.kafka_out_q');

    -- 3. Antrean Utama Masuk Aplikasi (Tipe JSON)
    DBMS_AQADM.CREATE_TRANSACTIONAL_EVENT_QUEUE(
        queue_name         => 'dev.in_q', 
        multiple_consumers => TRUE, 
        queue_payload_type => 'JSON'
    );
    DBMS_AQADM.START_QUEUE(queue_name => 'dev.in_q');

    -- 4. Antrean Jembatan masuk Kafka (Tipe JMS)
    DBMS_AQADM.CREATE_TRANSACTIONAL_EVENT_QUEUE(
        queue_name         => 'dev.kafka_in_q', 
        multiple_consumers => TRUE, 
        queue_payload_type => DBMS_AQADM.JMS_TYPE
    );
    DBMS_AQADM.START_QUEUE(queue_name => 'dev.kafka_in_q');
END;
/

SELECT name, queue_type, enqueue_enabled, dequeue_enabled FROM user_queues;
/

CREATE TABLE transaksi (
    no_rekening   VARCHAR2(20),
    nominal       NUMBER,
    status        VARCHAR2(20) DEFAULT 'CREATED',
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);
/

create or replace PACKAGE producer_pkg AS
    PROCEDURE catat_transaksi(p_no_rekening IN VARCHAR2, p_nominal IN NUMBER);
END producer_pkg;
/

create or replace PACKAGE BODY producer_pkg AS

    PROCEDURE catat_transaksi(p_no_rekening IN VARCHAR2, p_nominal IN NUMBER) IS
        enqueue_options    DBMS_AQ.ENQUEUE_OPTIONS_T;
        message_properties DBMS_AQ.MESSAGE_PROPERTIES_T;
        message_handle     RAW(16);
        msg                SYS.AQ$_JMS_TEXT_MESSAGE;
        v_payload          JSON;
    BEGIN
        -- 1. Logika bisnis utama
        INSERT INTO transaksi (no_rekening, nominal)
        VALUES (p_no_rekening, p_nominal);

        -- 2. Susun payload JSON sederhana
        v_payload := JSON('{"eventType":"TRANSACTION_CREATED","noRekening":"' || p_no_rekening || '","nominal":' || p_nominal || '}');

        -- 3. ENQUEUE -- ini yang membuat Oracle jadi Producer
        DBMS_AQ.ENQUEUE(
            queue_name         => 'dev.out_q',
            enqueue_options    => enqueue_options,
            message_properties => message_properties,
            payload            => v_payload,
            msgid              => message_handle
        );

        COMMIT;  -- INSERT transaksi dan ENQUEUE event commit bersama, atomic
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            RAISE;
    END catat_transaksi;

END producer_pkg;
/

CREATE TABLE tb_failed_events (
    fail_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_name    VARCHAR2(50),
    consumer_name VARCHAR2(50),
    msg_id        RAW(16),
    payload       JSON,
    error_msg     VARCHAR2(4000),
    retry_count   NUMBER DEFAULT 0,
    max_retry     NUMBER DEFAULT 3,
    status        VARCHAR2(20) DEFAULT 'FAILED', -- FAILED, RETRIED, DEAD_LETTER, ALARM
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);
/

create or replace PROCEDURE cb_bridge_out(
    context  RAW,
    reginfo  SYS.AQ$_REG_INFO,
    descr    SYS.AQ$_DESCRIPTOR,
    payload  RAW,
    payloadl NUMBER
) AS
    -- Variabel Dequeue (Membaca JSON)
    v_deq_opt          DBMS_AQ.DEQUEUE_OPTIONS_T;
    v_msg_props_in     DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id_in        RAW(16);
    v_payload_json     JSON;
    v_json_string      VARCHAR2(4000);

    -- Variabel Enqueue (Mengirim JMS)
    v_enq_opt          DBMS_AQ.ENQUEUE_OPTIONS_T;
    v_msg_props_out    DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id_out       RAW(16);
    v_payload_jms      SYS.AQ$_JMS_TEXT_MESSAGE;

    v_error_msg        VARCHAR2(4000);
    v_queue_name       VARCHAR2(128);
BEGIN
    -- 1. DEQUEUE dari antrean JSON
    v_deq_opt.consumer_name := 'BRIDGE_OUT_SVC';
    v_deq_opt.msgid         := descr.msg_id;

    DBMS_AQ.DEQUEUE(
        queue_name         => descr.queue_name, -- Ini akan bernilai 'dev.out_q'
        dequeue_options    => v_deq_opt,
        message_properties => v_msg_props_in,
        payload            => v_payload_json,
        msgid              => v_msg_id_in
    );

    -- 2. KONVERSI (JSON -> VARCHAR2 -> SYS.AQ$_JMS_TEXT_MESSAGE)
    v_json_string := JSON_SERIALIZE(v_payload_json);
    v_payload_jms := SYS.AQ$_JMS_TEXT_MESSAGE.construct;
    v_payload_jms.set_text(v_json_string);

    -- 3. ENQUEUE ke antrean jembatan JMS untuk dibaca Kafka Connect
    DBMS_AQ.ENQUEUE(
        queue_name         => 'dev.kafka_out_q',
        enqueue_options    => v_enq_opt,
        message_properties => v_msg_props_out,
        payload            => v_payload_jms,
        msgid              => v_msg_id_out
    );

    -- 4. SAHKAN TRANSAKSI
    COMMIT;

EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;

        v_error_msg  := SUBSTR('Error di Bridge Out: ' || SQLERRM, 1, 4000);
        v_queue_name := descr.queue_name;

        INSERT INTO dev.tb_failed_events (queue_name, consumer_name, error_msg)
        VALUES (v_queue_name, 'BRIDGE_OUT_SVC', v_error_msg);

        COMMIT;
END cb_bridge_out;
/

create or replace PROCEDURE cb_bridge_in(
    context  RAW, 
    reginfo  SYS.AQ$_REG_INFO, 
    descr    SYS.AQ$_DESCRIPTOR,
    payload  RAW, 
    payloadl NUMBER
) AS
    v_deq_opt          DBMS_AQ.DEQUEUE_OPTIONS_T;
    v_msg_props_in     DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id_in        RAW(16);

    v_payload_jms      SYS.AQ$_JMS_TEXT_MESSAGE;
    v_json_string      VARCHAR2(32767);

    v_enq_opt          DBMS_AQ.ENQUEUE_OPTIONS_T;
    v_msg_props_out    DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id_out       RAW(16);
    v_payload_json     JSON;

    v_error_msg        VARCHAR2(4000);
    v_queue_name       VARCHAR2(128);
BEGIN
    -- 1. Dequeue dari JMS
    v_deq_opt.consumer_name := 'BRIDGE_IN_SVC';
    v_deq_opt.msgid         := descr.msg_id;

    DBMS_AQ.DEQUEUE('dev.kafka_in_q', v_deq_opt, v_msg_props_in, v_payload_jms, v_msg_id_in);

    IF v_payload_jms IS NULL THEN COMMIT; RETURN; END IF;

    -- 2. Ekstrak string JMS
    v_json_string := v_payload_jms.text_vc;
    IF v_json_string IS NULL AND v_payload_jms.text_lob IS NOT NULL THEN
        v_json_string := DBMS_LOB.SUBSTR(v_payload_jms.text_lob, 4000, 1);
    END IF;

    IF v_json_string IS NULL THEN COMMIT; RETURN; END IF;

    -- 3. Konversi ke native JSON
    v_payload_json := JSON(v_json_string);

    -- 4. Enqueue ke in_q
    DBMS_AQ.ENQUEUE(
        queue_name         => 'dev.in_q',
        enqueue_options    => v_enq_opt,
        message_properties => v_msg_props_out, 
        payload            => v_payload_json,
        msgid              => v_msg_id_out
    );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;

        v_error_msg  := SUBSTR('Error di Bridge In: ' || SQLERRM, 1, 4000);
        v_queue_name := descr.queue_name;

        INSERT INTO dev.tb_failed_events (queue_name, consumer_name, error_msg)
        VALUES (v_queue_name, 'BRIDGE_IN_SVC', v_error_msg);

        COMMIT;
END cb_bridge_in;
/

create or replace PACKAGE     listener_pkg AS
    
    -- Prosedur dengan format standar Oracle AQ Notification
    PROCEDURE cb_process_event(
        context  RAW,
        reginfo  SYS.AQ$_REG_INFO,
        descr    SYS.AQ$_DESCRIPTOR,
        payload  RAW,
        payloadl NUMBER
    );

END listener_pkg;
/

create or replace PACKAGE BODY listener_pkg AS

    PROCEDURE cb_process_event(
        context  RAW,
        reginfo  SYS.AQ$_REG_INFO,
        descr    SYS.AQ$_DESCRIPTOR,
        payload  RAW,
        payloadl NUMBER
    ) IS
        v_dequeue_options    DBMS_AQ.DEQUEUE_OPTIONS_T;
        v_message_properties DBMS_AQ.MESSAGE_PROPERTIES_T;
        v_message_handle     RAW(16);
        v_payload            JSON;           

        v_no_rekening        VARCHAR2(20);
        v_error_msg          VARCHAR2(4000);
        v_queue_name         VARCHAR2(128);
    BEGIN
        -- 1. Siapkan opsi DEQUEUE berdasarkan trigger yang dikirim Oracle
        v_dequeue_options.msgid         := descr.msg_id;
        v_dequeue_options.consumer_name := descr.consumer_name;

        -- 2. Eksekusi DEQUEUE dari antrean (dev.in_q)
        DBMS_AQ.DEQUEUE(
            queue_name         => descr.queue_name,
            dequeue_options    => v_dequeue_options,
            message_properties => v_message_properties,
            payload            => v_payload,
            msgid              => v_message_handle
        );

        -- 3. Parsing JSON dan Eksekusi Logika Bisnis
        -- Karena v_payload sudah bertipe JSON, kita bisa langsung ekstrak datanya
        v_no_rekening := JSON_VALUE(v_payload, '$.noRekening');

        -- Lakukan Update status pada tabel transaksi
        UPDATE transaksi
        SET status = 'NOTIFIED'
        WHERE no_rekening = v_no_rekening
          AND status = 'CREATED';

        -- 4. SAHKAN TRANSAKSI
        COMMIT;

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;

            -- Tangkap error dengan aman
            v_error_msg  := SUBSTR('Error di Listener Utama: ' || SQLERRM, 1, 4000);
            v_queue_name := descr.queue_name;

            -- Catat error ke tabel log agar tidak hilang dan antrean tetap jalan
            INSERT INTO dev.tb_failed_events (queue_name, consumer_name, error_msg)
            VALUES (v_queue_name, descr.consumer_name, v_error_msg);

            COMMIT;
    END cb_process_event;

END listener_pkg;
/

BEGIN
    -- 1. Minta jembatan keluar mendengarkan out_q
    DBMS_AQADM.ADD_SUBSCRIBER(
        queue_name => 'dev.out_q', 
        subscriber => SYS.AQ$_AGENT('BRIDGE_OUT_SVC', NULL, 0)
    );

    DBMS_AQ.REGISTER(
        SYS.AQ$_REG_INFO_LIST(
            SYS.AQ$_REG_INFO(
                'dev.out_q:BRIDGE_OUT_SVC', 
                DBMS_AQ.NAMESPACE_AQ, 
                'plsql://dev.cb_bridge_out', 
                HEXTORAW('FF')
            )
        ), 
        1
    );

    -- 2. Tambahkan Subscriber khusus untuk Listener Utama
    DBMS_AQADM.ADD_SUBSCRIBER(
        queue_name => 'dev.in_q',
        subscriber => SYS.AQ$_AGENT('MAIN_LISTENER_SVC', NULL, 0)
    );

    DBMS_AQ.REGISTER(
        SYS.AQ$_REG_INFO_LIST(
            SYS.AQ$_REG_INFO(
                'dev.in_q:MAIN_LISTENER_SVC',
                DBMS_AQ.NAMESPACE_AQ,
                'plsql://dev.listener_pkg.cb_process_event',
                HEXTORAW('FF')
            )
        ),
        1
    );

    -- 3. Minta jembatan masuk mendengarkan kafka_in_q
    DBMS_AQADM.ADD_SUBSCRIBER(
        queue_name => 'dev.kafka_in_q',
        subscriber => SYS.AQ$_AGENT('BRIDGE_IN_SVC', NULL, 0)
    );

    DBMS_AQ.REGISTER(
        SYS.AQ$_REG_INFO_LIST(
            SYS.AQ$_REG_INFO(
                'dev.kafka_in_q:BRIDGE_IN_SVC',
                DBMS_AQ.NAMESPACE_AQ,
                'plsql://dev.cb_bridge_in',
                HEXTORAW('FF')
            )
        ),
        1
    );
END;
/



EXEC producer_pkg.catat_transaksi('000001', 100001);
/

SELECT msg_id, enq_time, msg_state, consumer_name FROM aq$out_q order by msg_id desc;
SELECT msg_id, enq_time, msg_state, consumer_name FROM aq$kafka_out_q order by msg_id desc;
SELECT msg_id, enq_time, msg_state, consumer_name FROM aq$kafka_in_q order by msg_id desc;
SELECT msg_id, enq_time, msg_state, consumer_name FROM aq$in_q order by msg_id desc;
SELECT object_name, status FROM user_objects WHERE object_name = 'CB_BRIDGE_OUT';
/

select * from tb_failed_events where consumer_name = 'BRIDGE_IN_SVC' order by fail_id desc;
/

SELECT no_rekening, status FROM transaksi;
/

DELETE FROM transaksi;
COMMIT;
/