CREATE TABLE tb_users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(100),
    points NUMBER DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'ACTIVE'
);
/

CREATE TABLE tb_email_logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    email_target VARCHAR2(100),
    pesan VARCHAR2(200),
    waktu_kirim TIMESTAMP DEFAULT SYSTIMESTAMP
);
/

BEGIN
    DBMS_AQADM.CREATE_TRANSACTIONAL_EVENT_QUEUE(
        queue_name          => 'USER_EVENT_Q',
        multiple_consumers  => TRUE, -- Ini wajib TRUE untuk Topic/Subscriber
        queue_payload_type  => 'JSON'
    );
    DBMS_AQADM.START_QUEUE(queue_name => 'USER_EVENT_Q');
END;
/

BEGIN
    -- Mendaftarkan Subscriber 1: Layanan Email
    DBMS_AQADM.ADD_SUBSCRIBER(
        queue_name => 'USER_EVENT_Q',
        subscriber => SYS.AQ$_AGENT('EMAIL_SERVICE', NULL, 0)
    );

    -- Mendaftarkan Subscriber 2: Layanan Poin
    DBMS_AQADM.ADD_SUBSCRIBER(
        queue_name => 'USER_EVENT_Q',
        subscriber => SYS.AQ$_AGENT('POINT_SERVICE', NULL, 0)
    );
END;
/

CREATE OR REPLACE PROCEDURE cb_email_service(
    context  RAW,
    reginfo  SYS.AQ$_REG_INFO,
    descr    SYS.AQ$_DESCRIPTOR,
    payload  RAW,
    payloadl NUMBER
) AS
    v_dequeue_options    DBMS_AQ.DEQUEUE_OPTIONS_T;
    v_message_props      DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id             RAW(16);
    v_payload            JSON;
    v_email              VARCHAR2(100);
BEGIN
    -- Beritahu Oracle bahwa kita mendequeue sebagai EMAIL_SERVICE
    v_dequeue_options.consumer_name := 'EMAIL_SERVICE';
    -- Kita hanya mengambil pesan dengan ID yang diberikan oleh trigger Oracle
    v_dequeue_options.msgid         := descr.msg_id;

    DBMS_AQ.DEQUEUE(
        queue_name         => descr.queue_name,
        dequeue_options    => v_dequeue_options,
        message_properties => v_message_props,
        payload            => v_payload,
        msgid              => v_msg_id
    );

    -- Ekstrak JSON
    v_email := JSON_VALUE(v_payload, '$.email');

    -- LOGIKA BISNIS: Simulasikan pengiriman email dengan insert ke tabel log
    INSERT INTO tb_email_logs (email_target, pesan) 
    VALUES (v_email, 'Selamat datang di sistem kami!');

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        -- Dalam production, Anda bisa mencatat error di sini
END cb_email_service;
/

CREATE OR REPLACE PROCEDURE cb_point_service(
    context  RAW,
    reginfo  SYS.AQ$_REG_INFO,
    descr    SYS.AQ$_DESCRIPTOR,
    payload  RAW,
    payloadl NUMBER
) AS
    v_dequeue_options    DBMS_AQ.DEQUEUE_OPTIONS_T;
    v_message_props      DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id             RAW(16);
    v_payload            JSON;
    v_user_id            NUMBER;
BEGIN
    -- Beritahu Oracle bahwa kita mendequeue sebagai POINT_SERVICE
    v_dequeue_options.consumer_name := 'POINT_SERVICE';
    v_dequeue_options.msgid         := descr.msg_id;

    DBMS_AQ.DEQUEUE(
        queue_name         => descr.queue_name,
        dequeue_options    => v_dequeue_options,
        message_properties => v_message_props,
        payload            => v_payload,
        msgid              => v_msg_id
    );

    -- Ekstrak JSON
    v_user_id := JSON_VALUE(v_payload, '$.user_id');

    -- LOGIKA BISNIS: Tambahkan 50 poin ke user tersebut
    UPDATE tb_users 
    SET points = points + 50 
    WHERE user_id = v_user_id;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
END cb_point_service;
/

CREATE OR REPLACE PROCEDURE cb_email_service(
    context  RAW,
    reginfo  SYS.AQ$_REG_INFO,
    descr    SYS.AQ$_DESCRIPTOR,
    payload  RAW,
    payloadl NUMBER
) AS
    v_dequeue_options    DBMS_AQ.DEQUEUE_OPTIONS_T;
    v_message_props      DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id             RAW(16);
    v_payload            JSON;
    v_email              VARCHAR2(100);
BEGIN
    -- Beritahu Oracle bahwa kita mendequeue sebagai EMAIL_SERVICE
    v_dequeue_options.consumer_name := 'EMAIL_SERVICE';
    -- Kita hanya mengambil pesan dengan ID yang diberikan oleh trigger Oracle
    v_dequeue_options.msgid         := descr.msg_id;

    DBMS_AQ.DEQUEUE(
        queue_name         => descr.queue_name,
        dequeue_options    => v_dequeue_options,
        message_properties => v_message_props,
        payload            => v_payload,
        msgid              => v_msg_id
    );

    -- Ekstrak JSON
    v_email := JSON_VALUE(v_payload, '$.email');

    -- LOGIKA BISNIS: Simulasikan pengiriman email dengan insert ke tabel log
    INSERT INTO tb_email_logs (email_target, pesan) 
    VALUES (v_email, 'Selamat datang di sistem kami!');

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        -- Dalam production, Anda bisa mencatat error di sini
END cb_email_service;
/

CREATE OR REPLACE PROCEDURE cb_point_service(
    context  RAW,
    reginfo  SYS.AQ$_REG_INFO,
    descr    SYS.AQ$_DESCRIPTOR,
    payload  RAW,
    payloadl NUMBER
) AS
    v_dequeue_options    DBMS_AQ.DEQUEUE_OPTIONS_T;
    v_message_props      DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id             RAW(16);
    v_payload            JSON;
    v_user_id            NUMBER;
BEGIN
    -- Beritahu Oracle bahwa kita mendequeue sebagai POINT_SERVICE
    v_dequeue_options.consumer_name := 'POINT_SERVICE';
    v_dequeue_options.msgid         := descr.msg_id;

    DBMS_AQ.DEQUEUE(
        queue_name         => descr.queue_name,
        dequeue_options    => v_dequeue_options,
        message_properties => v_message_props,
        payload            => v_payload,
        msgid              => v_msg_id
    );

    -- Ekstrak JSON
    v_user_id := JSON_VALUE(v_payload, '$.user_id');

    -- LOGIKA BISNIS: Tambahkan 50 poin ke user tersebut
    UPDATE tb_users 
    SET points = points + 50 
    WHERE user_id = v_user_id;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
END cb_point_service;
/

BEGIN
    -- Binding Subscriber Email ke Prosedur cb_email_service
    DBMS_AQ.REGISTER(
        SYS.AQ$_REG_INFO_LIST(
            SYS.AQ$_REG_INFO(
                'USER_EVENT_Q:EMAIL_SERVICE', -- Format: NAMA_QUEUE:NAMA_SUBSCRIBER
                DBMS_AQ.NAMESPACE_AQ,
                'plsql://cb_email_service',   -- Prosedur yang dipanggil
                HEXTORAW('FF')
            )
        ),
        1
    );

    -- Binding Subscriber Point ke Prosedur cb_point_service
    DBMS_AQ.REGISTER(
        SYS.AQ$_REG_INFO_LIST(
            SYS.AQ$_REG_INFO(
                'USER_EVENT_Q:POINT_SERVICE', 
                DBMS_AQ.NAMESPACE_AQ,
                'plsql://cb_point_service', 
                HEXTORAW('FF')
            )
        ),
        1
    );
END;
/

CREATE OR REPLACE PROCEDURE register_user(p_email IN VARCHAR2) AS
    v_user_id          NUMBER;
    v_enqueue_options  DBMS_AQ.ENQUEUE_OPTIONS_T;
    v_msg_props        DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id           RAW(16);
    v_payload          JSON;
BEGIN
    -- 1. Insert ke tabel (Proses Sinkron)
    INSERT INTO tb_users (email) 
    VALUES (p_email) 
    RETURNING user_id INTO v_user_id;

    -- 2. Siapkan Event Data
    v_payload := JSON('{' ||
                      '"event":"USER_REGISTERED",' ||
                      '"user_id":' || v_user_id || ',' ||
                      '"email":"' || p_email || '"' ||
                      '}');

    -- 3. Publish Event ke TxEventQ (Proses Asinkron)
    DBMS_AQ.ENQUEUE(
        queue_name         => 'USER_EVENT_Q',
        enqueue_options    => v_enqueue_options,
        message_properties => v_msg_props,
        payload            => v_payload,
        msgid              => v_msg_id
    );

    -- 4. Sahkan Transaksi
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Registrasi berhasil, event dikirim dengan ID: ' || RAWTOHEX(v_msg_id));
END;
/

BEGIN
    -- Mendaftarkan ulang HANYA untuk Point Service
    DBMS_AQ.REGISTER(
        SYS.AQ$_REG_INFO_LIST(
            SYS.AQ$_REG_INFO(
                'USER_EVENT_Q:POINT_SERVICE',  -- Pastikan nama antrean dan subscriber persis
                DBMS_AQ.NAMESPACE_AQ,
                'plsql://cb_point_service',    -- Pastikan nama prosedurnya benar
                HEXTORAW('FF')
            )
        ),
        1
    );
END;
/

ALTER PROCEDURE cb_point_service COMPILE;
GRANT EXECUTE ON cb_point_service TO PUBLIC;
REVOKE EXECUTE ON cb_point_service FROM PUBLIC;
/

DECLARE
    v_dequeue_options    DBMS_AQ.DEQUEUE_OPTIONS_T;
    v_message_props      DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id             RAW(16);
    v_payload            JSON;
    v_user_id            NUMBER;
BEGIN
    -- Menyamar sebagai Point Service
    v_dequeue_options.consumer_name := 'POINT_SERVICE';
    
    -- Ambil pesan teratas yang berstatus READY
    DBMS_AQ.DEQUEUE(
        queue_name         => 'USER_EVENT_Q',
        dequeue_options    => v_dequeue_options,
        message_properties => v_message_props,
        payload            => v_payload,
        msgid              => v_msg_id
    );

    -- Logika update point
    v_user_id := JSON_VALUE(v_payload, '$.user_id');
    
    UPDATE tb_users 
    SET points = points + 50 
    WHERE user_id = v_user_id;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Pesan yang nyangkut berhasil diproses manual!');
END;
/

EXEC register_user('raiz@example.com');
/

SELECT * FROM tb_users;
SELECT * FROM tb_email_logs;
/

SELECT msg_id, enq_time, msg_state, consumer_name 
FROM AQ$USER_EVENT_Q;