CREATE TABLE tb_users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR2(100),
    points NUMBER DEFAULT 0,
    status VARCHAR2(20) DEFAULT 'ACTIVE'
);
/

CREATE TABLE tb_email_logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    email_target VARCHAR2(100),
    pesan VARCHAR2(200),
    waktu_kirim TIMESTAMP DEFAULT SYSTIMESTAMP
);
/

BEGIN
    DBMS_AQADM.CREATE_TRANSACTIONAL_EVENT_QUEUE(
        queue_name          => 'USER_EVENT_Q',
        multiple_consumers  => TRUE, -- Ini wajib TRUE untuk Topic/Subscriber
        queue_payload_type  => 'JSON'
    );
    DBMS_AQADM.START_QUEUE(queue_name => 'USER_EVENT_Q');
END;
/

BEGIN
    -- Mendaftarkan Subscriber 1: Layanan Email
    DBMS_AQADM.ADD_SUBSCRIBER(
        queue_name => 'USER_EVENT_Q',
        subscriber => SYS.AQ$_AGENT('EMAIL_SERVICE', NULL, 0)
    );

    -- Mendaftarkan Subscriber 2: Layanan Poin
    DBMS_AQADM.ADD_SUBSCRIBER(
        queue_name => 'USER_EVENT_Q',
        subscriber => SYS.AQ$_AGENT('POINT_SERVICE', NULL, 0)
    );
END;
/

CREATE OR REPLACE PROCEDURE cb_email_service(
    context  RAW,
    reginfo  SYS.AQ$_REG_INFO,
    descr    SYS.AQ$_DESCRIPTOR,
    payload  RAW,
    payloadl NUMBER
) AS
    v_dequeue_options    DBMS_AQ.DEQUEUE_OPTIONS_T;
    v_message_props      DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id             RAW(16);
    v_payload            JSON;
    v_email              VARCHAR2(100);
BEGIN
    -- Beritahu Oracle bahwa kita mendequeue sebagai EMAIL_SERVICE
    v_dequeue_options.consumer_name := 'EMAIL_SERVICE';
    -- Kita hanya mengambil pesan dengan ID yang diberikan oleh trigger Oracle
    v_dequeue_options.msgid         := descr.msg_id;

    DBMS_AQ.DEQUEUE(
        queue_name         => descr.queue_name,
        dequeue_options    => v_dequeue_options,
        message_properties => v_message_props,
        payload            => v_payload,
        msgid              => v_msg_id
    );

    -- Ekstrak JSON
    v_email := JSON_VALUE(v_payload, '$.email');

    -- LOGIKA BISNIS: Simulasikan pengiriman email dengan insert ke tabel log
    INSERT INTO tb_email_logs (email_target, pesan) 
    VALUES (v_email, 'Selamat datang di sistem kami!');

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        -- Dalam production, Anda bisa mencatat error di sini
END cb_email_service;
/

CREATE OR REPLACE PROCEDURE cb_point_service(
    context  RAW,
    reginfo  SYS.AQ$_REG_INFO,
    descr    SYS.AQ$_DESCRIPTOR,
    payload  RAW,
    payloadl NUMBER
) AS
    v_dequeue_options    DBMS_AQ.DEQUEUE_OPTIONS_T;
    v_message_props      DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id             RAW(16);
    v_payload            JSON;
    v_user_id            NUMBER;
BEGIN
    -- Beritahu Oracle bahwa kita mendequeue sebagai POINT_SERVICE
    v_dequeue_options.consumer_name := 'POINT_SERVICE';
    v_dequeue_options.msgid         := descr.msg_id;

    DBMS_AQ.DEQUEUE(
        queue_name         => descr.queue_name,
        dequeue_options    => v_dequeue_options,
        message_properties => v_message_props,
        payload            => v_payload,
        msgid              => v_msg_id
    );

    -- Ekstrak JSON
    v_user_id := JSON_VALUE(v_payload, '$.user_id');

    -- LOGIKA BISNIS: Tambahkan 50 poin ke user tersebut
    UPDATE tb_users 
    SET points = points + 50 
    WHERE user_id = v_user_id;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
END cb_point_service;
/

CREATE OR REPLACE PROCEDURE cb_email_service(
    context  RAW,
    reginfo  SYS.AQ$_REG_INFO,
    descr    SYS.AQ$_DESCRIPTOR,
    payload  RAW,
    payloadl NUMBER
) AS
    v_dequeue_options    DBMS_AQ.DEQUEUE_OPTIONS_T;
    v_message_props      DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id             RAW(16);
    v_payload            JSON;
    v_email              VARCHAR2(100);
BEGIN
    -- Beritahu Oracle bahwa kita mendequeue sebagai EMAIL_SERVICE
    v_dequeue_options.consumer_name := 'EMAIL_SERVICE';
    -- Kita hanya mengambil pesan dengan ID yang diberikan oleh trigger Oracle
    v_dequeue_options.msgid         := descr.msg_id;

    DBMS_AQ.DEQUEUE(
        queue_name         => descr.queue_name,
        dequeue_options    => v_dequeue_options,
        message_properties => v_message_props,
        payload            => v_payload,
        msgid              => v_msg_id
    );

    -- Ekstrak JSON
    v_email := JSON_VALUE(v_payload, '$.email');

    -- LOGIKA BISNIS: Simulasikan pengiriman email dengan insert ke tabel log
    INSERT INTO tb_email_logs (email_target, pesan) 
    VALUES (v_email, 'Selamat datang di sistem kami!');

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        -- Dalam production, Anda bisa mencatat error di sini
END cb_email_service;
/

CREATE OR REPLACE PROCEDURE cb_point_service(
    context  RAW,
    reginfo  SYS.AQ$_REG_INFO,
    descr    SYS.AQ$_DESCRIPTOR,
    payload  RAW,
    payloadl NUMBER
) AS
    v_dequeue_options    DBMS_AQ.DEQUEUE_OPTIONS_T;
    v_message_props      DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id             RAW(16);
    v_payload            JSON;
    v_user_id            NUMBER;
BEGIN
    -- Beritahu Oracle bahwa kita mendequeue sebagai POINT_SERVICE
    v_dequeue_options.consumer_name := 'POINT_SERVICE';
    v_dequeue_options.msgid         := descr.msg_id;

    DBMS_AQ.DEQUEUE(
        queue_name         => descr.queue_name,
        dequeue_options    => v_dequeue_options,
        message_properties => v_message_props,
        payload            => v_payload,
        msgid              => v_msg_id
    );

    -- Ekstrak JSON
    v_user_id := JSON_VALUE(v_payload, '$.user_id');

    -- LOGIKA BISNIS: Tambahkan 50 poin ke user tersebut
    UPDATE tb_users 
    SET points = points + 50 
    WHERE user_id = v_user_id;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
END cb_point_service;
/

BEGIN
    -- Binding Subscriber Email ke Prosedur cb_email_service
    DBMS_AQ.REGISTER(
        SYS.AQ$_REG_INFO_LIST(
            SYS.AQ$_REG_INFO(
                'USER_EVENT_Q:EMAIL_SERVICE', -- Format: NAMA_QUEUE:NAMA_SUBSCRIBER
                DBMS_AQ.NAMESPACE_AQ,
                'plsql://cb_email_service',   -- Prosedur yang dipanggil
                HEXTORAW('FF')
            )
        ),
        1
    );

    -- Binding Subscriber Point ke Prosedur cb_point_service
    DBMS_AQ.REGISTER(
        SYS.AQ$_REG_INFO_LIST(
            SYS.AQ$_REG_INFO(
                'USER_EVENT_Q:POINT_SERVICE', 
                DBMS_AQ.NAMESPACE_AQ,
                'plsql://cb_point_service', 
                HEXTORAW('FF')
            )
        ),
        1
    );
END;
/

CREATE OR REPLACE PROCEDURE register_user(p_email IN VARCHAR2) AS
    v_user_id          NUMBER;
    v_enqueue_options  DBMS_AQ.ENQUEUE_OPTIONS_T;
    v_msg_props        DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id           RAW(16);
    v_payload          JSON;
BEGIN
    -- 1. Insert ke tabel (Proses Sinkron)
    INSERT INTO tb_users (email) 
    VALUES (p_email) 
    RETURNING user_id INTO v_user_id;

    -- 2. Siapkan Event Data
    v_payload := JSON('{' ||
                      '"event":"USER_REGISTERED",' ||
                      '"user_id":' || v_user_id || ',' ||
                      '"email":"' || p_email || '"' ||
                      '}');

    -- 3. Publish Event ke TxEventQ (Proses Asinkron)
    DBMS_AQ.ENQUEUE(
        queue_name         => 'USER_EVENT_Q',
        enqueue_options    => v_enqueue_options,
        message_properties => v_msg_props,
        payload            => v_payload,
        msgid              => v_msg_id
    );

    -- 4. Sahkan Transaksi
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Registrasi berhasil, event dikirim dengan ID: ' || RAWTOHEX(v_msg_id));
END;
/

BEGIN
    -- Mendaftarkan ulang HANYA untuk Point Service
    DBMS_AQ.REGISTER(
        SYS.AQ$_REG_INFO_LIST(
            SYS.AQ$_REG_INFO(
                'USER_EVENT_Q:POINT_SERVICE',  -- Pastikan nama antrean dan subscriber persis
                DBMS_AQ.NAMESPACE_AQ,
                'plsql://cb_point_service',    -- Pastikan nama prosedurnya benar
                HEXTORAW('FF')
            )
        ),
        1
    );
END;
/

EXEC register_user('budi@example.com');
SELECT * FROM tb_users;
SELECT * FROM tb_email_logs;
/





-- ====================================================================
-- 1. Tabel Idempotency (Mencegah eksekusi ganda saat retry)
CREATE TABLE tb_processed_events (
    msg_id        RAW(16),
    consumer_name VARCHAR2(50),
    processed_at  TIMESTAMP DEFAULT SYSTIMESTAMP,
    PRIMARY KEY (msg_id, consumer_name)
);

-- 2. Tabel Log Event Gagal (Dead Letter & Retry Queue)
CREATE TABLE tb_failed_events (
    fail_id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    queue_name    VARCHAR2(50),
    consumer_name VARCHAR2(50),
    msg_id        RAW(16),
    payload       JSON,
    error_msg     VARCHAR2(4000),
    retry_count   NUMBER DEFAULT 0,
    max_retry     NUMBER DEFAULT 3,
    status        VARCHAR2(20) DEFAULT 'FAILED', -- FAILED, RETRIED, DEAD_LETTER, ALARM
    created_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
    updated_at    TIMESTAMP DEFAULT SYSTIMESTAMP
);
/

CREATE OR REPLACE PROCEDURE cb_point_service(
    context  RAW,
    reginfo  SYS.AQ$_REG_INFO,
    descr    SYS.AQ$_DESCRIPTOR,
    payload  RAW,
    payloadl NUMBER
) AS
    v_dequeue_options    DBMS_AQ.DEQUEUE_OPTIONS_T;
    v_message_props      DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id             RAW(16);
    v_payload            JSON;
    v_user_id            NUMBER;
    v_already_processed  NUMBER := 0;
    v_error_msg          VARCHAR2(4000);
BEGIN
    -- 1. Dequeue Pesan
    v_dequeue_options.consumer_name := 'POINT_SERVICE';
    v_dequeue_options.msgid         := descr.msg_id;

    DBMS_AQ.DEQUEUE(
        queue_name         => descr.queue_name,
        dequeue_options    => v_dequeue_options,
        message_properties => v_message_props,
        payload            => v_payload,
        msgid              => v_msg_id
    );

    -- 2. CEK IDEMPOTENCY
    SELECT COUNT(*) INTO v_already_processed
    FROM tb_processed_events
    WHERE msg_id = v_msg_id AND consumer_name = 'POINT_SERVICE';

    IF v_already_processed > 0 THEN
        COMMIT; 
        RETURN;
    END IF;

    -- 3. LOGIKA BISNIS DENGAN ERROR HANDLING
    BEGIN
        v_user_id := JSON_VALUE(v_payload, '$.user_id');

        -- Eksekusi update
        UPDATE tb_users 
        SET points = points + 50 
        WHERE user_id = v_user_id;

        -- Jika tidak ada baris ter-update
        IF SQL%ROWCOUNT = 0 THEN
            RAISE_APPLICATION_ERROR(-20001, 'User ID ' || v_user_id || ' tidak ditemukan di tb_users.');
        END IF;

        -- Catat bahwa pesan ini SUKSES
        INSERT INTO tb_processed_events (msg_id, consumer_name) 
        VALUES (v_msg_id, 'POINT_SERVICE');

        COMMIT;

    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK; 
            
            -- Tangkap pesan error ke variabel lokal terlebih dahulu (Best Practice)
            v_error_msg := SUBSTR(SQLERRM, 1, 4000);
            
            -- Pindahkan pesan yang gagal ke tb_failed_events
            -- PASTIKAN STRUKTUR TABEL tb_failed_events SESUAI (Ada kolom queue_name, consumer_name, dll)
            INSERT INTO tb_failed_events (
                queue_name, 
                consumer_name, 
                msg_id, 
                payload, 
                error_msg, 
                status
            ) VALUES (
                descr.queue_name, 
                'POINT_SERVICE', 
                v_msg_id, 
                v_payload, 
                v_error_msg, 
                'FAILED'
            );
            
            COMMIT; 
    END;
END cb_point_service;
/

CREATE OR REPLACE PROCEDURE sp_reprocess_failed_events AS
    v_enqueue_options   DBMS_AQ.ENQUEUE_OPTIONS_T;
    v_message_props     DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_new_msg_id        RAW(16);
    v_reprocessed_count NUMBER := 0;
BEGIN
    FOR rec IN (
        SELECT fail_id, queue_name, payload, retry_count, max_retry
        FROM tb_failed_events
        WHERE status = 'FAILED'
        FOR UPDATE SKIP LOCKED -- Mencegah bentrokan jika dijalankan bersamaan
    ) LOOP
        -- Jika percobaan sudah mencapai batas maksimal, tandai sebagai DEAD_LETTER
        IF rec.retry_count >= rec.max_retry THEN
            UPDATE tb_failed_events
            SET status = 'DEAD_LETTER',
                updated_at = SYSTIMESTAMP
            WHERE fail_id = rec.fail_id;
        ELSE
            -- Kirim ulang (Re-Enqueue) payload JSON ke antrean utama
            DBMS_AQ.ENQUEUE(
                queue_name         => rec.queue_name,
                enqueue_options    => v_enqueue_options,
                message_properties => v_message_props,
                payload            => rec.payload,
                msgid              => v_new_msg_id
            );

            -- Perbarui status event
            UPDATE tb_failed_events
            SET retry_count = retry_count + 1,
                status      = 'RETRIED',
                updated_at  = SYSTIMESTAMP
            WHERE fail_id = rec.fail_id;

            v_reprocessed_count := v_reprocessed_count + 1;
        END IF;
    END LOOP;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Total event dikirim ulang: ' || v_reprocessed_count);
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END sp_reprocess_failed_events;
/

CREATE OR REPLACE PROCEDURE sp_sweeper_job AS
    v_stuck_count NUMBER := 0;
BEGIN
    -- 1. Jalankan pemrosesan ulang untuk event gagal yang masih memiliki kuota retry
    sp_reprocess_failed_events;

    -- 2. DETEKSI EVENT NYANGKUT: Cek antrean jika ada status READY > 15 menit
    SELECT COUNT(*) INTO v_stuck_count
    FROM AQ$USER_EVENT_Q
    WHERE msg_state = 'READY'
      AND enq_time < SYSTIMESTAMP - INTERVAL '15' MINUTE;

    -- 3. Jika ada event tersangkut, catat peringatan alarm
    IF v_stuck_count > 0 THEN
        INSERT INTO tb_failed_events (
            queue_name, consumer_name, error_msg, status
        ) VALUES (
            'USER_EVENT_Q', 
            'SYSTEM_SWEEPER', 
            'PERINGATAN: Terdapat ' || v_stuck_count || ' event berstatus READY tersangkut lebih dari 15 menit!', 
            'ALARM'
        );
        COMMIT;
    END IF;
END sp_sweeper_job;
/

GRANT CREATE JOB TO dev;
/

BEGIN
    DBMS_SCHEDULER.create_job(
        job_name        => 'JOB_TXEVENTQ_SWEEPER',
        job_type        => 'STORED_PROCEDURE',
        job_action      => 'sp_sweeper_job',
        start_date      => SYSTIMESTAMP,
        repeat_interval => 'FREQ=MINUTELY; INTERVAL=15',
        enabled         => TRUE,
        comments        => 'Otomatis memproses ulang event gagal dan memantau event nyangkut'
    );
END;
/

SELECT
    consumer_name AS "Layanan Tujuan (Subscriber)",
    COUNT(DECODE(msg_state, 'READY', 1)) AS "Antre (Belum Diproses)",
    COUNT(DECODE(msg_state, 'PROCESSED', 1)) AS "Selesai (Menunggu Cleanup)",
    COUNT(DECODE(msg_state, 'EXPIRED', 1)) AS "Kedaluwarsa (Gagal Internal)",
    MIN(CASE WHEN msg_state = 'READY' THEN enq_time ELSE NULL END) AS "Antrean Terlama",
    ROUND((SYSDATE - CAST(MIN(CASE WHEN msg_state = 'READY' THEN enq_time ELSE NULL END) AS DATE)) * 24 * 60, 2) AS "Lama Antrean Terlama (Menit)"
FROM
    dev.AQ$USER_EVENT_Q
WHERE
    consumer_name IS NOT NULL
GROUP BY
    consumer_name
ORDER BY
    "Antre (Belum Diproses)" DESC;
/

BEGIN
    -- Membuat Queue Khusus Outbound Kafka (Tipe JMS)
    DBMS_AQADM.CREATE_TRANSACTIONAL_EVENT_QUEUE(
        queue_name          => 'KAFKA_OUTBOUND_Q',
        multiple_consumers  => FALSE, -- Kafka Connect langsung ambil tanpa perlu langganan
        queue_payload_type  => DBMS_AQADM.JMS_TYPE
    );
    DBMS_AQADM.START_QUEUE(queue_name => 'KAFKA_OUTBOUND_Q');
END;
/

BEGIN
    -- Daftarkan agen penjembatan
    DBMS_AQADM.ADD_SUBSCRIBER(
        queue_name => 'USER_EVENT_Q',
        subscriber => SYS.AQ$_AGENT('KAFKA_BRIDGE_SVC', NULL, 0)
    );
END;
/

CREATE OR REPLACE PROCEDURE cb_kafka_bridge(
    context  RAW,
    reginfo  SYS.AQ$_REG_INFO,
    descr    SYS.AQ$_DESCRIPTOR,
    payload  RAW,
    payloadl NUMBER
) AS
    -- Variabel untuk DEQUEUE (Antrean JSON)
    v_deq_opt          DBMS_AQ.DEQUEUE_OPTIONS_T;
    v_msg_props_in     DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id_in        RAW(16);
    v_payload_json     JSON;           
    v_json_text        VARCHAR2(4000); 

    -- Variabel untuk ENQUEUE (Antrean JMS)
    v_enq_opt          DBMS_AQ.ENQUEUE_OPTIONS_T;
    v_msg_props_out    DBMS_AQ.MESSAGE_PROPERTIES_T;
    v_msg_id_out       RAW(16);
    v_payload_jms      SYS.AQ$_JMS_TEXT_MESSAGE; 
    
    -- Variabel penampung untuk Error Handling
    v_error_msg        VARCHAR2(4000);
    v_queue_name       VARCHAR2(128);
BEGIN
    -- 1. DEQUEUE PESAN DARI ANTREAN JSON (USER_EVENT_Q)
    v_deq_opt.consumer_name := 'KAFKA_BRIDGE_SVC';
    v_deq_opt.msgid         := descr.msg_id;

    DBMS_AQ.DEQUEUE(
        queue_name         => descr.queue_name,
        dequeue_options    => v_deq_opt,
        message_properties => v_msg_props_in,
        payload            => v_payload_json,
        msgid              => v_msg_id_in
    );

    -- 2. PROSES KONVERSI: JSON -> STRING -> JMS_TEXT_MESSAGE
    
    -- A. Ubah tipe native JSON menjadi VARCHAR2
    v_json_text := JSON_SERIALIZE(v_payload_json);

    -- B. Konstruksi / Bangun struktur pesan JMS Oracle
    v_payload_jms := SYS.AQ$_JMS_TEXT_MESSAGE.construct;
    
    -- C. Isi pesan JMS dengan string JSON tadi
    v_payload_jms.set_text(v_json_text);

    -- 3. ENQUEUE PESAN KE ANTREAN KAFKA (KAFKA_OUTBOUND_Q)
    DBMS_AQ.ENQUEUE(
        queue_name         => 'KAFKA_OUTBOUND_Q',
        enqueue_options    => v_enq_opt,
        message_properties => v_msg_props_out,
        payload            => v_payload_jms,
        msgid              => v_msg_id_out
    );

    -- 4. COMMIT!
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        
        -- Tangkap nilai ke variabel skalar sebelum proses INSERT
        v_error_msg  := SUBSTR('Error di Bridge: ' || SQLERRM, 1, 4000);
        v_queue_name := descr.queue_name;
        
        -- Catat ke tabel error menggunakan variabel skalar
        INSERT INTO tb_failed_events (queue_name, consumer_name, error_msg)
        VALUES (v_queue_name, 'KAFKA_BRIDGE_SVC', v_error_msg);
        
        COMMIT;
END cb_kafka_bridge;
/

BEGIN
    DBMS_AQ.REGISTER(
        SYS.AQ$_REG_INFO_LIST(
            SYS.AQ$_REG_INFO(
                'USER_EVENT_Q:KAFKA_BRIDGE_SVC', -- Antrean Utama JSON
                DBMS_AQ.NAMESPACE_AQ,
                'plsql://cb_kafka_bridge',       -- Panggil prosedur penjembatan
                HEXTORAW('FF')
            )
        ),
        1
    );
END;
/

EXEC register_user('hisbi@example.com');
/

SELECT * FROM tb_users;
SELECT * FROM tb_email_logs;
/

SELECT msg_id, enq_time, msg_state, consumer_name 
FROM AQ$USER_EVENT_Q;

SELECT msg_id, enq_time, msg_state, consumer_name
FROM dev.AQ$KAFKA_OUTBOUND_Q;